---
title: "p8105_hw6_mk4208"
author: "Meeraj Kothari"
date: "11/19/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading libraries

```{r message=FALSE}
library(tidyverse)
library(modelr)
library(mlbench)
library(caret)
library(patchwork)
```


# Problem 1 

```{r}
birthweight = read_csv("./Data/birthweight.csv") %>% janitor::clean_names() %>% 
  mutate(babysex = factor(babysex, c(1, 2), c("Male", "Female")),
         frace = factor(frace, c(1:4, 8, 9), c("White", "Black", "Asian", "Puerto Rican", "Other", "Unkown")),
         malform = factor(malform, c(0, 1), c("Absent", "Present")),
         mrace = factor(mrace, c(1:4, 8), c("White", "Black", "Asian", "Puerto Rican", "Other")))
```

```{r message=FALSE, warning=FALSE}
set.seed(10)

nums = map(birthweight, is.numeric) %>% unlist()

correlationMatrix = birthweight %>% select_if(is.numeric) %>% cor()

highlyCorrelated = correlationMatrix %>% findCorrelation(cutoff = 0.7)

birthweight_no_corr = birthweight %>% select(-highlyCorrelated, "bwt")

control = trainControl(method = "repeatedcv", number = 10, repeats = 3)

model = train(bwt~., data = birthweight_no_corr, method = "glm", preProcess = "scale", trControl = control)

importance = varImp(model, scale = FALSE)

ggplot(importance) + 
  theme_minimal()
```

```{r}
fit = lm(bwt ~ bhead + delwt + gaweeks + smoken + mrace + babysex, data = birthweight)
```

```{r}
birthweight %>% 
  modelr::add_residuals(fit) %>% 
  modelr::add_predictions(fit) %>% 
  ggplot(aes(x = pred, y = resid)) +
  geom_point() + 
  theme_minimal()
```

```{r}
comparison_1 = lm(bwt ~ blength + gaweeks, data = birthweight)

comparison_2 = lm(bwt ~ bhead + blength + babysex + bhead*blength + blength*babysex + babysex*bhead + bhead*blength*babysex, data = birthweight) 

cv_df = 
  crossv_mc(birthweight, 100) %>% 
  mutate(
    train = map(train, as_tibble), 
    test = map(test, as_tibble))

cv_df = cv_df %>%
  mutate(fit = map(train, ~lm(bwt ~ bhead + delwt + gaweeks + smoken + mrace + babysex, data = .x)),
         comparison_1 = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
         comparison_2 = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead*blength + blength*babysex + babysex*bhead + bhead*blength*babysex, data = .x))) %>% 
  mutate(rmse_fit = map2_dbl(fit, test, ~rmse(model = .x, data = .y)),
         rmse_comparison_1 = map2_dbl(comparison_1, test, ~rmse(model = .x, data = .y)),
         rmse_comparison_2 = map2_dbl(comparison_2, test, ~rmse(model = .x, data = .y)))
```


```{r}
cv_df %>% 
  select(starts_with("rmse")) %>%
  pivot_longer(
    everything(), 
    names_to = "model",
    values_to = "rmse", 
    names_prefix = "rmse_") %>%
  mutate(model = fct_inorder(model)) %>%
  ggplot(aes(x = model, y = rmse)) + 
  geom_violin()
```

# Problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
results = weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~ lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::tidy),
    glance = map(models, broom::glance)) %>% 
  select(results, glance, .id) %>% 
  unnest(results) %>% 
  pivot_wider( 
    names_from = term,
    values_from = c(estimate, std.error, glance),
    id_cols = .id, 
    ) %>%
  janitor::clean_names() %>%
  unnest(c(glance_intercept, .names_repair)) %>% 
  mutate(
    log_b0_b1 = log(estimate_intercept * estimate_tmin)
  ) 
```

```{r}
p1 = results %>% 
  ggplot(aes(x = r.squared)) + 
  geom_histogram() + 
  geom_density() +
  theme_minimal() 

p2 = results %>% 
  ggplot(aes(x = log_b0_b1)) + 
  geom_histogram() + 
  geom_density() +
  theme_minimal()

p1 + p2
```


